.PHONY: clean All

All:
	@echo "----------Building project:[ Client_project - Debug ]----------"
	@cd "Client_project" && "$(MAKE)" -f  "Client_project.mk"
clean:
	@echo "----------Cleaning project:[ Client_project - Debug ]----------"
	@cd "Client_project" && "$(MAKE)" -f  "Client_project.mk" clean
